on:
  pull_request:
      branches:
      - main

jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        use: actions/checkout@v3   

      - name: Add dependencies
        run: npm install

      - name: Cypress run
        use: cypress-io/github-action@v6
        with:
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}